#! /bin/bash

# download directory
if [ "$(type -t __make_and_cd_tar_dir)" = "function" ] ; then
    __make_and_cd_tar_dir
fi

VER_NAME="cmake-3.13.2.tar.gz"

if [[ ! -f "$VER_NAME" ]];then 
    wget --no-check-certificate -O "$VER_NAME" https://cmake.org/files/v3.13/$VER_NAME
fi


tar xzvf $VER_NAME

cd ${VER_NAME:0:(-7)}

./configure --prefix="$INSTALL_PREFIX/cmake" 
make && make install

bin_path="export PATH=/usr/local/cmake/bin:$PATH"
echo "$bin_path" > /etc/profile.d/cmake.sh 
source /etc/profile.d/cmake.sh 

# remove old version
yum remove cmake -y

cmake --version
