#!/usr/bin/bash

if [[ -z "$TAR_DIR" ]]
then
    TAR_DIR="$ROOT_DIR/storage/tar"
    mkdir -p $TAR_DIR
fi
    
#cd "${TAR_DIR}"
if [ -d "$PREFIX/php"  ]
then
    echo "PHP is already installed."
    exit 0
fi

if [ ! -f "php-7.1.11.tar.gz" ];then 
    wget --no-check-certificate -O php-7.1.11.tar.gz http://cn2.php.net/get/php-7.1.11.tar.gz/from/this/mirror
fi

tar -xzvf php-7.1.11.tar.gz 

cd php-7.1.11

if [[ "$?" -ne 0 ]];then
    echo "not found directory 'php-7.1.11'"
    exit 1
fi

./configure --prefix=/usr/local/php \
--with-curl \
--with-freetype-dir \
--with-gd \
--with-iconv-dir \
--with-kerberos \
--with-libdir=lib64 \
--with-libxml-dir=/usr \
--with-openssl \
--with-pcre-regex \
--with-pdo-mysql \
--with-pdo-sqlite \
--with-pear \
--with-png-dir \
--with-jpeg-dir \
--with-xmlrpc \
--with-xsl \
--with-zlib \
--with-bz2 \
--with-mhash \
--enable-fpm \
--enable-bcmath \
--enable-libxml \
--with-imap-ssl \
--with-mcrypt \
--enable-mbstring \
--enable-maintainer-zts \
--with-config-file-path=/etc \
--with-config-file-scan-dir=/etc/php.d \
--enable-mbstring \
--enable-xml \
--enable-sockets \
--enable-pcntl \
--enable-sysvmsg \
--enable-sysvshm \
--enable-shmop \
--enable-mysqlnd \
--enable-soap \
--enable-opcache \
--enable-zip \
--enable-sysvmsg \
--enable-sysvsem \
--enable-sysvshm \
--enable-shmop \
--enable-zend-multibyte \
--enable-ftp

#--enable-dtrace
# --disable-fileinfo

# 禁用传递其他运行库搜索路径
#--disable-rpath 

# 禁止调试模式 
# --disable-debug

#  virtual memory exhausted: Cannot allocate memory
#  add --disable-fileinfo

if [[ "$?" -ne 0 ]];then
    echo "php compile failure"
    exit 1
fi


make  && make install

if [[ "$?" -ne 0 ]];then
    echo "php install failure "
    exit 1
fi


