#!/usr/bin/bash

if [[ -z "$TAR_DIR" ]]
then
    TAR_DIR="$ROOT_DIR/storage/tar"
    mkdir -p $TAR_DIR
fi
    
cd "${TAR_DIR}"

if [[ -d "$INSTALL_PREFIX/php"  ]]
then
    echo "PHP is already installed."
    exit 0
fi

S_VER_NAME="php-7.2.9.tar.gz"

if [[ ! -f "$S_VER_NAME" ]];then 
    wget --no-check-certificate -O "$S_VER_NAME" http://cn2.php.net/get/"$S_VER_NAME"/from/this/mirror
fi

tar -xzvf "$S_VER_NAME" 

cd ${S_VER_NAME:0:(-7)}

if [[ "$?" -ne 0 ]];then
    echo "Not found directory '${S_VER_NAME:0:(-7)}'"
    exit 1
fi

./configure --prefix="$INSTALL_PREFIX/php" \
--with-curl \
--with-freetype-dir \
--with-gd \
--with-iconv-dir \
--with-kerberos \
--with-libdir=lib64 \
--with-libxml-dir=/usr \
--with-openssl \
--with-pcre-regex \
--with-pdo-mysql \
--with-pdo-sqlite \
--with-pear \
--with-png-dir \
--with-jpeg-dir \
--with-xmlrpc \
--with-xsl \
--with-zlib \
--with-bz2 \
--with-mhash \
--enable-fpm \
--enable-bcmath \
--enable-libxml \
--with-imap-ssl \
--with-mcrypt \
--enable-mbstring \
--enable-maintainer-zts \
--with-config-file-path=/etc \
--with-config-file-scan-dir=/etc/php.d \
--enable-mbstring \
--enable-xml \
--enable-sockets \
--enable-pcntl \
--enable-sysvmsg \
--enable-sysvshm \
--enable-shmop \
--enable-mysqlnd \
--enable-soap \
--enable-opcache \
--enable-zip \
--enable-sysvmsg \
--enable-sysvsem \
--enable-sysvshm \
--enable-shmop \
--enable-zend-multibyte \
--enable-ftp

#--enable-dtrace
# --disable-fileinfo

# 禁用传递其他运行库搜索路径
#--disable-rpath 

# 禁止调试模式 
# --disable-debug

#  virtual memory exhausted: Cannot allocate memory
#  add --disable-fileinfo

if [[ "$?" -ne 0 ]];then
    log_error "PHP compilation failed."
    exit 1
fi


make  && make install

if [[ "$?" -ne 0 ]];then
    log_error "PHP compilation failed."
    exit 1
fi

log_success "PHP install success."

