#!/usr/bin/bash

__detection_of_php_extensions 'yaf'

if [[ "$?" -eq 0 ]];then
    __echo_warning "Already install extension 【 yaf 】."
    exit 0
fi

if [[ -z "$TAR_DIR" ]]
then
    TAR_DIR="$ROOT_DIR/storage/tar"
    mkdir -p $TAR_DIR
fi

cd "${TAR_DIR}"

if [[ ! -f "yaf-3.0.7.tgz" ]];then
    wget -O yaf-3.0.7.tgz http://pecl.php.net/get/yaf-3.0.7.tgz
fi

tar -xzvf yaf-3.0.7.tgz

cd yaf-3.0.7

if [[ "$?" -ne 0 ]]
then
    __echo_warning "Not found directory yaf-3.0.7"
    exit 1
fi

/usr/local/php/bin/phpize

./configure --with-php-config=/usr/local/php/bin/php-config

make && make install

if [[ "$?" -eq 0 ]];then
    echo "extension=yaf.so" >> /etc/php.ini
    __echo_success "Yaf install success"
fi

cat<<EOF
add config to php.ini :
[yaf] 
yaf.use_namespace=1
yaf.environ=product 
yaf.use_spl_autoload=1 
yaf.name_suffix=0 
yaf.forward_limit=5 
EOF
