#!/bin/bash

VER_NAME="node-v9.9.0-linux-x64.tar.xz"
INS_NAME=$(echo $VER_NAME|cut -d "-" -f1)
VER_INS_DIR="$INSTALL_PREFIX/$INS_NAME"

# Checks whether node is installed 
__geecoo_is_install $INS_NAME 

__geecoo_install_wget "$VER_NAME" "https://nodejs.org/dist/v9.9.0/$VER_NAME" 

tar -xvf "$VER_NAME" && mv  ${VER_NAME:0:(-7)} "$VER_INS_DIR"

__geecoo_install_finished $INS_NAME

echo "export PATH=$VER_INS_DIR/bin:\$PATH" > /etc/profile.d/$INS_NAME.sh
.  /etc/profile.d/node.sh

