#!/bin/bash

VER_NAME="node-v9.9.0.tar.gz"
INS_NAME=$(echo $VER_NAME|cut -d "-" -f1)
VER_INS_DIR="$INSTALL_PREFIX/$INS_NAME"

# Checks whether node is installed 
__geecoo_is_install $INS_NAME 

__geecoo_install "$VER_NAME" "https://nodejs.org/dist/v9.9.0/$VER_NAME" 

./configure --prefix=$VER_INS_DIR 

make && make install

__geecoo_install_finished $INS_NAME

echo "export PATH=$VER_INS_DIR/bin:\$PATH" > /etc/profile.d/$INS_NAME.sh
.  /etc/profile.d/node.sh
